// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskFlow.Infrastructure;

#nullable disable

namespace TaskFlow.Infrastructure.Migrations
{
    [DbContext(typeof(TaskFlowDbContext))]
    [Migration("20260422164414_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TaskFlow.Domain.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ivan@example.com",
                            FullName = "Ivan Hnetylo",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "manager@example.com",
                            FullName = "Olena Manager",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Email = "member@example.com",
                            FullName = "Andrii Member",
                            Role = "Member"
                        });
                });

            modelBuilder.Entity("TaskFlow.Domain.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ASP.NET Core cross-cutting student project",
                            Name = "Course Project",
                            OwnerId = 1
                        });
                });

            modelBuilder.Entity("TaskFlow.Domain.TaskComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkTaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("WorkTaskId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("TaskFlow.Domain.WorkTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssigneeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssigneeId = 1,
                            Description = "Create entities, DbContext and relations",
                            DueDate = new DateTime(2026, 4, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProjectId = 1,
                            Status = 2,
                            Title = "Build EF Core model"
                        },
                        new
                        {
                            Id = 2,
                            AssigneeId = 2,
                            Description = "Create CRUD endpoints with DTO validation",
                            DueDate = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProjectId = 1,
                            Status = 1,
                            Title = "Expose Web API"
                        });
                });

            modelBuilder.Entity("TaskFlow.Domain.Project", b =>
                {
                    b.HasOne("TaskFlow.Domain.AppUser", "Owner")
                        .WithMany("Projects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TaskFlow.Domain.TaskComment", b =>
                {
                    b.HasOne("TaskFlow.Domain.AppUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskFlow.Domain.WorkTask", "WorkTask")
                        .WithMany("Comments")
                        .HasForeignKey("WorkTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("WorkTask");
                });

            modelBuilder.Entity("TaskFlow.Domain.WorkTask", b =>
                {
                    b.HasOne("TaskFlow.Domain.AppUser", "Assignee")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskFlow.Domain.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TaskFlow.Domain.AppUser", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("TaskFlow.Domain.Project", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TaskFlow.Domain.WorkTask", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
